export const cardValues = {
  cardBack: 0,
  aceClubs: 11,
  twoClubs: 2,
  threeClubs: 3,
  fourClubs: 4,
  fiveClubs: 5,
  sixClubs: 6,
  sevenClubs: 7,
  eightClubs: 8,
  nineClubs: 9,
  tenClubs: 10,
  jackClubs: 10,
  queenClubs: 10,
  kingClubs: 10,
  aceSpades: 11,
  twoSpades: 2,
  threeSpades: 3,
  fourSpades: 4,
  fiveSpades: 5,
  sixSpades: 6,
  sevenSpades: 7,
  eightSpades: 8,
  nineSpades: 9,
  tenSpades: 10,
  jackSpades: 10,
  queenSpades: 10,
  kingSpades: 10,
  aceHearts: 11,
  twoHearts: 2,
  threeHearts: 3,
  fourHearts: 4,
  fiveHearts: 5,
  sixHearts: 6,
  sevenHearts: 7,
  eightHearts: 8,
  nineHearts: 9,
  tenHearts: 10,
  jackHearts: 10,
  queenHearts: 10,
  kingHearts: 10,
  aceDiamonds: 11,
  twoDiamonds: 2,
  threeDiamonds: 3,
  fourDiamonds: 4,
  fiveDiamonds: 5,
  sixDiamonds: 6,
  sevenDiamonds: 7,
  eightDiamonds: 8,
  nineDiamonds: 9,
  tenDiamonds: 10,
  jackDiamonds: 10,
  queenDiamonds: 10,
  kingDiamonds: 10,
};

export const newDeck = [
  'aceClubs',
  'twoClubs',
  'threeClubs',
  'fourClubs',
  'fiveClubs',
  'sixClubs',
  'sevenClubs',
  'eightClubs',
  'nineClubs',
  'tenClubs',
  'jackClubs',
  'queenClubs',
  'kingClubs',
  'aceSpades',
  'twoSpades',
  'threeSpades',
  'fourSpades',
  'fiveSpades',
  'sixSpades',
  'sevenSpades',
  'eightSpades',
  'nineSpades',
  'tenSpades',
  'jackSpades',
  'queenSpades',
  'kingSpades',
  'aceHearts',
  'twoHearts',
  'threeHearts',
  'fourHearts',
  'fiveHearts',
  'sixHearts',
  'sevenHearts',
  'eightHearts',
  'nineHearts',
  'tenHearts',
  'jackHearts',
  'queenHearts',
  'kingHearts',
  'aceDiamonds',
  'twoDiamonds',
  'threeDiamonds',
  'fourDiamonds',
  'fiveDiamonds',
  'sixDiamonds',
  'sevenDiamonds',
  'eightDiamonds',
  'nineDiamonds',
  'tenDiamonds',
  'jackDiamonds',
  'queenDiamonds',
  'kingDiamonds',
  'aceClubs',
  'twoClubs',
  'threeClubs',
  'fourClubs',
  'fiveClubs',
  'sixClubs',
  'sevenClubs',
  'eightClubs',
  'nineClubs',
  'tenClubs',
  'jackClubs',
  'queenClubs',
  'kingClubs',
  'aceSpades',
  'twoSpades',
  'threeSpades',
  'fourSpades',
  'fiveSpades',
  'sixSpades',
  'sevenSpades',
  'eightSpades',
  'nineSpades',
  'tenSpades',
  'jackSpades',
  'queenSpades',
  'kingSpades',
  'aceHearts',
  'twoHearts',
  'threeHearts',
  'fourHearts',
  'fiveHearts',
  'sixHearts',
  'sevenHearts',
  'eightHearts',
  'nineHearts',
  'tenHearts',
  'jackHearts',
  'queenHearts',
  'kingHearts',
  'aceDiamonds',
  'twoDiamonds',
  'threeDiamonds',
  'fourDiamonds',
  'fiveDiamonds',
  'sixDiamonds',
  'sevenDiamonds',
  'eightDiamonds',
  'nineDiamonds',
  'tenDiamonds',
  'jackDiamonds',
  'queenDiamonds',
  'kingDiamonds',
];

export const aces = ['aceClubs', 'aceSpades', 'aceHearts', 'aceDiamonds'];
